### ISSUE TITLE
named references test failures

### ISSUE THREAD

**Issue by zaach** [zaach/ebnf-parser#4]
Hey @cdibbs, I'm getting tests failures on the new feature. Were these passing for you? Are you using jison 0.4.10?

```
    test named group ()
      ⚡ Error: Parse error on line 1:
      one, two
      ^
      Expecting 'word[alice]', got 'word'
          at typal_constructor.parseError (/Users/zcarter/repos/ebnf-parser/node_modules/jison/lib/jison.js:1185:15)
          at typal_constructor.parse (/Users/zcarter/repos/ebnf-parser/node_modules/jison/lib/jison.js:1301:22)
          at /Users/zcarter/repos/ebnf-parser/tests/ebnf.js:62:39
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:29:20)
          at next (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:69:7)
          at Object.end (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:25:7)
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:41:28)
          at next (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:69:7)
          at Object.end (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:25:7)
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:41:28)
    test named option (?)
      ⚡ Error: Parse error on line 1:
      oneor two
      ^
      Expecting 'word[alex]', got 'word'
          at typal_constructor.parseError (/Users/zcarter/repos/ebnf-parser/node_modules/jison/lib/jison.js:1185:15)
          at typal_constructor.parse (/Users/zcarter/repos/ebnf-parser/node_modules/jison/lib/jison.js:1301:22)
          at /Users/zcarter/repos/ebnf-parser/tests/ebnf.js:62:39
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:29:20)
          at next (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:69:7)
          at Object.end (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:25:7)
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:46:14)
          at next (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:69:7)
          at Object.end (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:25:7)
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:41:28)
    test named complex expression (())
      ⚡ Error: Parse error on line 1:
      one two three four, 
      ^
      Expecting 'word[alpha]', got 'word'
          at typal_constructor.parseError (/Users/zcarter/repos/ebnf-parser/node_modules/jison/lib/jison.js:1185:15)
          at typal_constructor.parse (/Users/zcarter/repos/ebnf-parser/node_modules/jison/lib/jison.js:1301:22)
          at /Users/zcarter/repos/ebnf-parser/tests/ebnf.js:62:39
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:29:20)
          at next (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:69:7)
          at Object.end (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:25:7)
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:46:14)
          at next (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:69:7)
          at Object.end (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:25:7)
          at test (/Users/zcarter/repos/ebnf-parser/node_modules/test/test.js:46:14)
```

**Comment by cdibbs** [comment]
Yes, these were all passing. The mods to ebnf-parser require the changes in jison. I just pulled down two fresh copies to be sure. Here is the other pull request: https://github.com/zaach/jison/pull/181. Note that I (believe I) fixed the speed issues in the token stack enhancement, too, but we can get rid of that if it hinders the named references enhancement.

**Comment by zaach** [comment]
@cdibbs Yes, could we decouple the PRs? I intend to make the token stack optional either way, like other parser features.

**Comment by cdibbs** [comment]
@zaach Sorry about that. I'm still pretty new to git/github. I can work on making the token stack optional as I find time, later.

**Comment by cdibbs** [comment]
@zaach Thought I'd check in on this - were you ever able to get this working? https://github.com/zaach/jison/pull/185 decouples the PRs. I looked over what I was doing, and the biggest gotcha was that I temporarily sym-linked the updated Jison module into the ebnf-parser node_modules directory before rebuilding ebnf-parser (not sure whether there's a better way to do this). Without the Jison changes at the BNF level, the EBNF stuff cannot work.

**Comment by zaach** [comment]
Oh, I didn't notice the new PR. I'll test it out locally – thanks!
